#!/bin/bash
#xinput enable 'Elan Touchpad'
en=$(xinput list-props 11 | grep 'Device Enabled' | cut -d: -f2)
if [ $en -eq 1 ];
then
  notify-send "Touchpad off" &
        xinput disable 11
else
  notify-send "Touchpad on" &
        xinput enable 11
fi


