#!/bin/bash
#xinput enable 'SynPS/2 Synaptics TouchPad'
en=$(xinput list-props 'SynPS/2 Synaptics TouchPad' | grep 'Device Enabled' | cut -d: -f2)
if [ $en -eq 1 ];
then
	#notify-send "Touchpad off" &
        xinput disable 'SynPS/2 Synaptics TouchPad'
else
	#notify-send "Touchpad on" &
        xinput enable 'SynPS/2 Synaptics TouchPad'
fi


